-- Adicionar suplementos essenciais que faltam na base de dados

-- Proteínas
INSERT INTO public.supplements (id, name, category, description, benefits, target_symptoms, dosage_min, dosage_max, dosage_unit, timing, evidence_level, contraindications, interactions) VALUES
('whey-protein', 'Whey Protein', 'amino_acid', 'Proteína do soro do leite de alta qualidade e rápida absorção, rica em aminoácidos essenciais e BCAA.', 
ARRAY['Ganho de massa muscular', 'Recuperação pós-treino', 'Síntese proteica', 'Melhoria da performance'], 
ARRAY['Fadiga', 'Recuperação lenta pós-treino', 'Falta de energia'], 
20, 50, 'g', 'with_meal', 'strong', 
ARRAY['Alergia ao leite', 'Intolerância à lactose severa'], 
ARRAY['Pode reduzir absorção de alguns medicamentos se tomado simultaneamente']),

('caseina', 'Caseína', 'amino_acid', 'Proteína de digestão lenta derivada do leite, ideal para fornecimento prolongado de aminoácidos.', 
ARRAY['Ganho de massa muscular', 'Recuperação noturna', 'Saciedade prolongada', 'Manutenção muscular'], 
ARRAY['Fadiga', 'Recuperação lenta pós-treino', 'Falta de energia'], 
20, 40, 'g', 'evening', 'strong', 
ARRAY['Alergia ao leite', 'Intolerância à lactose'], 
ARRAY['Pode interferir na absorção de minerais se consumida em excesso']),

('proteina-vegetal', 'Proteína Vegetal', 'amino_acid', 'Blend de proteínas vegetais (ervilha, arroz, hemp) com perfil completo de aminoácidos.', 
ARRAY['Ganho de massa muscular', 'Recuperação pós-treino', 'Digestão fácil', 'Opção vegana'], 
ARRAY['Fadiga', 'Recuperação lenta pós-treino', 'Problemas digestivos'], 
20, 40, 'g', 'with_meal', 'moderate', 
ARRAY['Alergia a leguminosas específicas'], 
ARRAY['Raramente interage com medicamentos']),

('albumina', 'Albumina', 'amino_acid', 'Proteína da clara do ovo desidratada, com alto valor biológico e digestão intermediária.', 
ARRAY['Ganho de massa muscular', 'Recuperação pós-treino', 'Baixo custo', 'Rica em leucina'], 
ARRAY['Fadiga', 'Recuperação lenta pós-treino'], 
15, 30, 'g', 'with_meal', 'strong', 
ARRAY['Alergia ao ovo'], 
ARRAY['Pode reduzir absorção de biotina em altas doses']),

('colageno-hidrolisado', 'Colágeno Hidrolisado', 'amino_acid', 'Peptídeos de colágeno de fácil absorção para saúde da pele, articulações e ossos.', 
ARRAY['Saúde da pele', 'Saúde articular', 'Fortalecimento ósseo', 'Elasticidade da pele'], 
ARRAY['Dores articulares', 'Problemas de pele', 'Recuperação lenta pós-treino'], 
10, 20, 'g', 'any', 'moderate', 
ARRAY['Alergia a peixes ou bovinos dependendo da origem'], 
ARRAY['Geralmente bem tolerado']),

('colageno-tipos-1-2-3', 'Colágeno Tipos I, II e III', 'amino_acid', 'Blend completo dos principais tipos de colágeno para suporte estrutural completo.', 
ARRAY['Saúde articular', 'Saúde da pele', 'Fortalecimento de cartilagens', 'Saúde óssea'], 
ARRAY['Dores articulares', 'Problemas de pele', 'Dores musculares'], 
5, 15, 'g', 'any', 'moderate', 
ARRAY['Alergia a frutos do mar ou bovinos'], 
ARRAY['Bem tolerado pela maioria das pessoas']),

-- Suplementos do Sono
('melatonina', 'Melatonina', 'other', 'Hormônio natural que regula o ciclo circadiano e melhora a qualidade do sono.', 
ARRAY['Melhoria do sono', 'Regulação do ritmo circadiano', 'Propriedades antioxidantes', 'Redução do jet lag'], 
ARRAY['Insônia', 'Ansiedade', 'Estresse excessivo'], 
0.5, 10, 'mg', 'evening', 'strong', 
ARRAY['Gravidez', 'Amamentação', 'Doenças autoimunes', 'Uso de anticoagulantes'], 
ARRAY['Sedativos', 'Anticoagulantes', 'Medicamentos para diabetes']),

('magnesio-glicinato', 'Magnésio Glicinato', 'mineral', 'Forma altamente biodisponível de magnésio ligado à glicina para melhor absorção e tolerância.', 
ARRAY['Melhoria do sono', 'Relaxamento muscular', 'Redução do estresse', 'Saúde cardiovascular'], 
ARRAY['Insônia', 'Ansiedade', 'Cãibras musculares', 'Estresse excessivo'], 
200, 400, 'mg', 'evening', 'strong', 
ARRAY['Problemas renais graves'], 
ARRAY['Antibióticos', 'Medicamentos para osteoporose']),

-- Superalimentos
('spirulina', 'Spirulina', 'other', 'Microalga azul-verde rica em proteínas, vitaminas, minerais e antioxidantes.', 
ARRAY['Fortalecimento imunológico', 'Energia natural', 'Desintoxicação', 'Rico em proteínas'], 
ARRAY['Fadiga', 'Baixa imunidade', 'Falta de energia'], 
1, 8, 'g', 'morning', 'moderate', 
ARRAY['Fenilcetonúria', 'Doenças autoimunes'], 
ARRAY['Anticoagulantes', 'Imunossupressores']),

('chlorella', 'Chlorella', 'other', 'Microalga verde rica em clorofila, vitaminas e minerais com propriedades desintoxicantes.', 
ARRAY['Desintoxicação', 'Fortalecimento imunológico', 'Saúde digestiva', 'Rico em clorofila'], 
ARRAY['Fadiga', 'Baixa imunidade', 'Problemas digestivos'], 
2, 10, 'g', 'morning', 'moderate', 
ARRAY['Alergia a algas', 'Problemas de coagulação'], 
ARRAY['Anticoagulantes', 'Medicamentos fotossensibilizantes']),

('acai', 'Açaí', 'other', 'Fruto amazônico rico em antioxidantes, antocianinas e gorduras saudáveis.', 
ARRAY['Propriedades antioxidantes', 'Energia natural', 'Saúde cardiovascular', 'Anti-envelhecimento'], 
ARRAY['Fadiga', 'Estresse excessivo', 'Baixa imunidade'], 
5, 15, 'g', 'morning', 'moderate', 
ARRAY['Alergia a frutas vermelhas'], 
ARRAY['Geralmente bem tolerado']),

('maca-peruana', 'Maca Peruana', 'herb', 'Raiz andina adaptógena que melhora energia, resistência e equilíbrio hormonal.', 
ARRAY['Aumento da energia', 'Melhoria da libido', 'Equilíbrio hormonal', 'Resistência física'], 
ARRAY['Fadiga', 'Estresse excessivo', 'Baixa energia', 'Mudanças de humor'], 
1.5, 6, 'g', 'morning', 'moderate', 
ARRAY['Problemas hormonais sensíveis', 'Hipertensão'], 
ARRAY['Medicamentos hormonais']),

('cloreto-magnesio', 'Cloreto de Magnésio', 'mineral', 'Forma de magnésio com boa biodisponibilidade para múltiplas funções corporais.', 
ARRAY['Saúde óssea', 'Função muscular', 'Saúde cardiovascular', 'Metabolismo energético'], 
ARRAY['Cãibras musculares', 'Fadiga', 'Ansiedade'], 
200, 400, 'mg', 'with_meal', 'strong', 
ARRAY['Problemas renais', 'Diarreia crônica'], 
ARRAY['Antibióticos', 'Diuréticos']),

-- Digestão
('psyllium', 'Psyllium', 'other', 'Fibra solúvel natural que melhora a saúde digestiva e regula o colesterol.', 
ARRAY['Saúde digestiva', 'Regulação do colesterol', 'Controle da glicemia', 'Saciedade'], 
ARRAY['Problemas digestivos', 'Constipação'], 
5, 15, 'g', 'with_meal', 'strong', 
ARRAY['Obstrução intestinal', 'Dificuldade de deglutição'], 
ARRAY['Pode reduzir absorção de medicamentos']),

('fibra-acacia', 'Fibra de Acácia', 'other', 'Fibra solúvel prebiótica suave que nutre a microbiota intestinal.', 
ARRAY['Saúde digestiva', 'Crescimento de bactérias benéficas', 'Bem tolerada', 'Prebiótico natural'], 
ARRAY['Problemas digestivos', 'Baixa imunidade'], 
5, 20, 'g', 'with_meal', 'moderate', 
ARRAY['Alergia à acácia'], 
ARRAY['Raramente causa interações']),

('enzimas-digestivas', 'Enzimas Digestivas', 'other', 'Complexo enzimático que auxilia na digestão de proteínas, carboidratos e gorduras.', 
ARRAY['Melhoria da digestão', 'Redução de gases', 'Absorção de nutrientes', 'Conforto digestivo'], 
ARRAY['Problemas digestivos', 'Gases', 'Má digestão'], 
1, 3, 'cápsulas', 'with_meal', 'moderate', 
ARRAY['Úlceras ativas', 'Alergia a componentes específicos'], 
ARRAY['Medicamentos antiácidos podem reduzir eficácia']),

('betaina-hcl', 'Betaína HCl', 'other', 'Suplemento que aumenta a acidez estomacal para melhor digestão de proteínas.', 
ARRAY['Melhoria da digestão proteica', 'Absorção de B12', 'Saúde estomacal'], 
ARRAY['Problemas digestivos', 'Má digestão', 'Fadiga'], 
200, 650, 'mg', 'with_meal', 'moderate', 
ARRAY['Úlceras', 'Gastrite', 'Uso de antiácidos'], 
ARRAY['Antiácidos', 'Inibidores da bomba de prótons']),

-- Antioxidantes
('resveratrol', 'Resveratrol', 'other', 'Polifenol antioxidante encontrado em uvas com propriedades anti-envelhecimento.', 
ARRAY['Propriedades antioxidantes', 'Saúde cardiovascular', 'Anti-envelhecimento', 'Proteção celular'], 
ARRAY['Estresse excessivo', 'Envelhecimento'], 
100, 500, 'mg', 'with_meal', 'moderate', 
ARRAY['Gravidez', 'Problemas de coagulação'], 
ARRAY['Anticoagulantes', 'Medicamentos para pressão']),

('pterostilbeno', 'Pterostilbeno', 'other', 'Antioxidante similar ao resveratrol mas com melhor biodisponibilidade.', 
ARRAY['Propriedades antioxidantes', 'Saúde cognitiva', 'Controle da glicemia', 'Anti-inflamatório'], 
ARRAY['Dificuldade de concentração', 'Estresse excessivo'], 
50, 250, 'mg', 'with_meal', 'moderate', 
ARRAY['Gravidez', 'Amamentação'], 
ARRAY['Medicamentos para diabetes']),

('astaxantina', 'Astaxantina', 'other', 'Carotenoide antioxidante potente derivado de microalgas com propriedades anti-inflamatórias.', 
ARRAY['Propriedades antioxidantes', 'Saúde da pele', 'Proteção UV', 'Saúde ocular'], 
ARRAY['Problemas de pele', 'Fadiga', 'Estresse excessivo'], 
4, 12, 'mg', 'with_meal', 'moderate', 
ARRAY['Alergia a crustáceos ou algas'], 
ARRAY['Pode potencializar efeitos de anticoagulantes']),

('licopeno', 'Licopeno', 'other', 'Carotenoide antioxidante encontrado em tomates com benefícios cardiovasculares.', 
ARRAY['Saúde cardiovascular', 'Proteção da próstata', 'Propriedades antioxidantes', 'Saúde da pele'], 
ARRAY['Estresse excessivo', 'Problemas de pele'], 
10, 30, 'mg', 'with_meal', 'moderate', 
ARRAY['Alergia a tomates'], 
ARRAY['Geralmente bem tolerado']),

-- Óleos Especializados  
('oleo-peixe-concentrado', 'Óleo de Peixe Concentrado', 'other', 'Óleo de peixe purificado e concentrado em EPA e DHA para máxima potência.', 
ARRAY['Saúde cardiovascular', 'Função cerebral', 'Anti-inflamatório', 'Saúde ocular'], 
ARRAY['Problemas de concentração', 'Estresse excessivo', 'Fadiga'], 
1000, 3000, 'mg', 'with_meal', 'strong', 
ARRAY['Alergia a peixes', 'Problemas de coagulação'], 
ARRAY['Anticoagulantes', 'Medicamentos para pressão']),

('oleo-krill', 'Óleo de Krill', 'other', 'Óleo extraído do krill antártico, rico em fosfolipídios e astaxantina.', 
ARRAY['Saúde cardiovascular', 'Função cerebral', 'Propriedades antioxidantes', 'Melhor absorção'], 
ARRAY['Problemas de concentração', 'Fadiga', 'Estresse excessivo'], 
500, 2000, 'mg', 'with_meal', 'moderate', 
ARRAY['Alergia a crustáceos'], 
ARRAY['Anticoagulantes']),

('oleo-mct', 'Óleo MCT', 'other', 'Triglicerídeos de cadeia média de rápida absorção para energia imediata.', 
ARRAY['Energia rápida', 'Função cerebral', 'Controle de peso', 'Cetose'], 
ARRAY['Fadiga', 'Dificuldade de concentração', 'Falta de energia'], 
15, 45, 'ml', 'morning', 'moderate', 
ARRAY['Problemas hepáticos', 'Diabetes não controlado'], 
ARRAY['Pode causar desconforto digestivo inicial']);