// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehjpdcbyoqaoazknymbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoanBkY2J5b3Fhb2F6a255bWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MzY4MjksImV4cCI6MjA3MzQxMjgyOX0.R0YYIR1U58LC8AVGJbSPykF4Tpb1UDjsVNZZqj7Jkh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});